trigger: none


pr: none


variables:
- name: devEnvironment
  value: 'dev'
# TODO: provide an email address for the ExampleWorkflow to an send mail to
- name: toEmailAddress
  value: ''

stages:
- stage: Build

  displayName: 'Build Artifact'

  jobs:
  - job: logic_app_build
    displayName: 'Build and publish logic app'
    steps:
    - task: CopyFiles@2
      displayName: 'Create project folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/20220630-DevOps-Pipeline-Test/logic-app-flow'
        Contents: |
          host.json
          connections.json
          devops_blob_connection/**
          devops_sql_apiconnection/**
          Recurrence_Trigger/**
          
          
        TargetFolder: '$(System.DefaultWorkingDirectory)/20220630-DevOps-Pipeline-Test/project_output'

    - task: ArchiveFiles@2
      displayName: 'Create project zip'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/20220630-DevOps-Pipeline-Test/project_output'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish project zip artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: 'logicAppCIArtifact'
        publishLocation: 'pipeline'


- stage: Deployment

  displayName: 'Deploy logic app'

  jobs:
  - job: logic_app_deploy
    displayName: 'Deploy logic app'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'logicAppCIArtifact'
        path: '$(Build.ArtifactStagingDirectory)'
    - script: dir
      workingDirectory: $(Build.ArtifactStagingDirectory)
      displayName: List contents of a folder
    - task: AzureFunctionApp@1
      displayName: 'Deploy logic app workflows'
      inputs:
        azureSubscription: 'serena'
        ConnectedServiceName: 'serena'
        resourceGroupName: 'Serena-DevOps-logicappV2-deployment'
        location: 'eastus'
        appType: 'functionApp,workflowapp'
        appName: 'serenacicdtest'
        # package: '$(Pipeline.Workspace)/logicAppCIArtifact/$(Build.BuildId).zip'
        appSettings: '-Environment $(devEnvironment) -emailAddress $(toEmailAddress)'
        package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

        deploymentMethod: 'runFromPackage'
